# Generated by Django 3.1.6 on 2021-02-19 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followers', to='core.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BandProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(blank=True, max_length=100, null=True)),
                ('band_instruments', models.CharField(blank=True, max_length=100, null=True)),
                ('band_bio', models.TextField(blank=True, null=True)),
                ('band_members', models.CharField(blank=True, max_length=100, null=True)),
                ('band_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('band_size', models.CharField(blank=True, max_length=100, null=True)),
                ('band_location', models.CharField(blank=True, max_length=100, null=True)),
                ('years_active', models.CharField(blank=True, max_length=100, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followers', to='core.BandProfile')),
            ],
        ),
    ]
