# Generated by Django 3.1.7 on 2021-02-24 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedInstruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='individualorband',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Band', 'Band')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wanted_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vacancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wanted_instruments',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.WantedInstruments'),
        ),
    ]
