# Generated by Django 3.1.7 on 2021-02-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210224_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wanted_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
