# Generated by Django 3.1.7 on 2021-02-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210222_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='author',
            new_name='ind',
        ),
    ]
