# Generated by Django 3.1.7 on 2021-02-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210225_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wanted_instruments',
            field=models.ManyToManyField(null=True, to='core.WantedInstruments'),
        ),
    ]
