# Generated by Django 3.1.7 on 2021-02-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210222_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandInstruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_instruments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bandprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BandGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bandprofile')),
            ],
        ),
    ]
