# Generated by Django 3.1.7 on 2021-02-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bandgenre_bandinstruments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandinstruments',
            name='band_instruments',
        ),
        migrations.DeleteModel(
            name='BandGenre',
        ),
        migrations.DeleteModel(
            name='BandInstruments',
        ),
    ]
