# Generated by Django 3.1.7 on 2021-02-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210225_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wanted_instruments',
            field=models.ManyToManyField(blank=True, to='core.WantedInstruments'),
        ),
    ]
