# Generated by Django 3.1.7 on 2021-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210225_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wanted_instruments',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.WantedInstruments'),
        ),
        migrations.AlterField(
            model_name='wantedinstruments',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
