# Generated by Django 3.1.7 on 2021-02-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210222_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_genres', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BandInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_instruments', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruments', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bandprofile',
            name='band_instruments',
        ),
        migrations.RemoveField(
            model_name='bandprofile',
            name='band_genre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instrument',
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='band_instrument',
            field=models.ManyToManyField(blank=True, to='core.BandInstrument'),
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='band_genre',
            field=models.ManyToManyField(blank=True, to='core.BandGenre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genre',
            field=models.ManyToManyField(blank=True, to='core.IndGenre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instrument',
            field=models.ManyToManyField(blank=True, to='core.IndInstrument'),
        ),
    ]
