# Generated by Django 3.1.7 on 2021-02-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210223_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandprofile',
            name='band_genre',
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='band_genre',
            field=models.CharField(choices=[('Classical', 'Classical'), ('Rock', 'Rock'), ('Blues', 'Blues'), ('Country', 'Country'), ('Metal', 'Metal'), ('Pop', 'Pop'), ('Reggae', 'Reggae'), ('Latin', 'Latin'), ('R&B/Soul', 'R&B/Soul'), ('Hip-Hop/Rap', 'Hip-Hop/Rap'), ('Electronic', 'Electronic'), ('Rock and Roll', 'Rock and Roll'), ('Dance', 'Dance'), ('Jazz', 'Jazz'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='bandprofile',
            name='band_instrument',
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='band_instrument',
            field=models.CharField(choices=[('Guitar', 'Guitar'), ('Piano', 'Piano'), ('Bass', 'Bass'), ('Drums', 'Drums'), ('Keyboard', 'Keyboard'), ('Banjo', 'Banjo'), ('Vocals', 'Vocals'), ('Trumpet', 'Trumpet'), ('Acoustic Guitar', 'Acoustic Guitar'), ('Electric Guitar', 'Electric Guitar'), ('Woodwinds', 'Woodwinds'), ('Percussions', 'Percussions'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='genre',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(choices=[('Classical', 'Classical'), ('Rock', 'Rock'), ('Blues', 'Blues'), ('Country', 'Country'), ('Metal', 'Metal'), ('Pop', 'Pop'), ('Reggae', 'Reggae'), ('Latin', 'Latin'), ('R&B/Soul', 'R&B/Soul'), ('Hip-Hop/Rap', 'Hip-Hop/Rap'), ('Electronic', 'Electronic'), ('Rock and Roll', 'Rock and Roll'), ('Dance', 'Dance'), ('Jazz', 'Jazz'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instrument',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instrument',
            field=models.CharField(choices=[('Guitar', 'Guitar'), ('Piano', 'Piano'), ('Bass', 'Bass'), ('Drums', 'Drums'), ('Keyboard', 'Keyboard'), ('Banjo', 'Banjo'), ('Vocals', 'Vocals'), ('Trumpet', 'Trumpet'), ('Acoustic Guitar', 'Acoustic Guitar'), ('Electric Guitar', 'Electric Guitar'), ('Woodwinds', 'Woodwinds'), ('Percussions', 'Percussions'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BandGenre',
        ),
        migrations.DeleteModel(
            name='BandInstrument',
        ),
        migrations.DeleteModel(
            name='IndGenre',
        ),
        migrations.DeleteModel(
            name='IndInstrument',
        ),
    ]
