# Generated by Django 3.1.7 on 2021-02-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210223_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='ind_bio',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='ind_genre',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='zipcode',
            new_name='ind_instrument',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instrument',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ind_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ind_zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bandprofile',
            name='band_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bandprofile',
            name='band_instrument',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
