# Generated by Django 3.1.7 on 2021-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
