# Generated by Django 3.1.7 on 2021-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210223_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bandprofile',
            name='band_genre',
        ),
        migrations.RemoveField(
            model_name='bandprofile',
            name='band_instrument',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ind_genre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ind_instrument',
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='band_genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='bands', to='core.Genre'),
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='band_instrument',
            field=models.ManyToManyField(blank=True, null=True, related_name='bands', to='core.Instrument'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ind_genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='core.Genre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ind_instrument',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='core.Instrument'),
        ),
    ]
