# Generated by Django 3.1.7 on 2021-02-25 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210225_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
