# Generated by Django 3.1.7 on 2021-02-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210223_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandprofile',
            name='band_genre',
            field=models.ManyToManyField(blank=True, related_name='bands', to='core.Genre'),
        ),
        migrations.AlterField(
            model_name='bandprofile',
            name='band_instrument',
            field=models.ManyToManyField(blank=True, related_name='bands', to='core.Instrument'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ind_genre',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.Genre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ind_instrument',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.Instrument'),
        ),
    ]
