# Generated by Django 3.1.7 on 2021-02-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_messages_read_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='read_by',
            new_name='read',
        ),
    ]
