# Generated by Django 3.1.7 on 2021-02-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210223_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandprofile',
            old_name='band_genre',
            new_name='band_genres',
        ),
        migrations.RenameField(
            model_name='bandprofile',
            old_name='band_instrument',
            new_name='band_instruments',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ind_genre',
            new_name='ind_genres',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ind_instrument',
            new_name='ind_instruments',
        ),
    ]
