# Generated by Django 3.1.7 on 2021-02-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210225_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='read',
        ),
        migrations.AddField(
            model_name='messages',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
