# Generated by Django 3.1.7 on 2021-03-01 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210301_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.ManyToManyField(null=True, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
