# Generated by Django 3.1.7 on 2021-03-01 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210301_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
