# Generated by Django 3.1.7 on 2021-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210301_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='receiver_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
