# Generated by Django 3.1.7 on 2021-03-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sender_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
