# Generated by Django 3.1.7 on 2021-03-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210304_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='sender_name',
            new_name='name',
        ),
    ]
