# Generated by Django 3.1.7 on 2021-03-05 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210305_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='display_for_user',
            field=models.ManyToManyField(null=True, related_name='display', to=settings.AUTH_USER_MODEL),
        ),
    ]
