# Generated by Django 3.1.7 on 2021-03-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210305_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='display_for_user',
        ),
    ]
