# Generated by Django 3.1.7 on 2021-03-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_messages_display_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
    ]
