# Generated by Django 3.1.7 on 2021-03-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210308_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
