# Generated by Django 3.1.7 on 2021-03-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_messages_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
