# Generated by Django 3.1.7 on 2021-03-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_messages_display_for_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_complete',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
