# Generated by Django 3.1.7 on 2021-03-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210309_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spotify',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
